name = "rand_sys"
description = "Random number generator from system entropy"
version = "0.1.0"

authors = ["César SAGAERT"]
maintainers = ["César SAGAERT <sagaert@adacore.com>"]
maintainers-logins = ["AldanTanneo"]
licenses = "GPL-3.0-or-later"
website = "https://github.com/AldanTanneo/rand-ada"
tags = []

[[depends-on]]
rand_core = "~0.1.0"

[[pins]]
rand_core = { path='../rand_core' }

[[depends-on]]
system_random = "^1.0.0"
