name = "rand_core"
description = "Core interfaces for random number generation"
version = "0.1.0"

authors = ["César SAGAERT"]
maintainers = ["César SAGAERT <sagaert@adacore.com>"]
maintainers-logins = ["AldanTanneo"]
licenses = "GPL-3.0-or-later"
website = "https://github.com/AldanTanneo/rand-ada"
tags = []
