name = "rand_chacha"
description = "ChaCha20/12/8 based PRNG"
version = "0.1.0"

authors = ["César SAGAERT"]
maintainers = ["César SAGAERT <sagaert@adacore.com>"]
maintainers-logins = ["AldanTanneo"]
licenses = "GPL-3.0-or-later"
website = "https://github.com/AldanTanneo/rand-ada"
tags = []

[[depends-on]]
rand_core = "~0.1.0"

[[pins]]
rand_core = { path = "../rand_core" }
