name: CI

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/.gitignore"
      - "README.md"
  push:
    branches: [main]
    paths-ignore:
      - "**/.gitignore"
      - "README.md"
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: alire-project/setup-alire@v5
        with:
          version: "nightly"
      - run: alr test
